var Config = {
  CANVAS_HEIGHT: 320,
  CANVAS_WIDTH: 640,
  BACKGROUND_COLOR: 'hsl(0, 20%, 15%)',
  
  DEFAULT_MAP_ROWS: 10,
  DEFAULT_MAP_COLS: 10,
  TILE_HEIGHT: 32,
  TILE_WIDTH: 32,
  
  DEFAULT_CAMERA_SPEED: 10,
  CAMERA_MIN_SPEED: 0,
  CAMERA_MAX_SPEED: 20,
  CAMERA_MIN_ZOOM: -100,
  CAMERA_MAX_ZOOM: 100,
  DEBUG_CAMERA: false,

  IMAGE_DIR: 'images/',
};